name: Build Vault TUI with Nuitka

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: rockylinux:9
    steps:
      - name: Install System Dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb
          dnf install -y python3.11 python3.11-devel gcc binutils patchelf
          python3.11 -m ensurepip

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -e ".[build]"

      - name: Compile for linux
        run: |
          python3.11 -m nuitka --output-dir=bin/linux --standalone --output-filename=v4t --include-data-file=app.tcss=app.tcss --onefile app.py

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux Build
          path: bin/linux/v4t

  # Windows build on standard runner
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[build]"

      - name: Compile for windows
        run: |
          nuitka --output-dir=bin/windows --output-filename=v4t --standalone --onefile --include-data-file=app.tcss=app.tcss --mingw64 --assume-yes-for-downloads app.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: bin/windows/v4t.exe
